#pragma once

#define BOARD_I2C_SDA_PIN 0
#define BOARD_I2C_SCL_PIN 1

#define BOARD_BUTTON_1_PIN 2
#define BOARD_BUTTON_2_PIN 3

#define BOARD_RED_LED_PIN 4
#define BOARD_GREEN_LED_PIN 5

#define BOARD_ADC0_PIN 6
#define BOARD_ADC1_PIN 7

#define BOARD_MUX_SEL0_PIN 8
#define BOARD_MUX_SEL1_PIN 9

#define BOARD_ETH_TX_EN_PIN 10
#define BOARD_ETH_TXD0_PIN 11
#define BOARD_ETH_TXD1_PIN 12

// Adjusted to match actual PCB wiring: CRS_DV is on GPIO13
#define BOARD_ETH_RXD0_PIN 15
#define BOARD_ETH_RXD1_PIN 14
#define BOARD_ETH_CRS_DV_PIN 13

#define BOARD_LAN8720_MDIO_PIN 16
#define BOARD_LAN8720_MDC_PIN 17
#define BOARD_LAN8720_RESET_PIN 18

#define BOARD_I2S_BCLK_PIN 19
#define BOARD_I2S_LRCLK_PIN 20
#define BOARD_I2S_DATA_PIN 21

#define BOARD_EXTRA_GPIO_22_PIN 22
#define BOARD_ETH_REFCLK_PIN 23
#define BOARD_EXTRA_GPIO_24_PIN 24
#define BOARD_EXTRA_GPIO_25_PIN 25
#define BOARD_EXTRA_GPIO_26_PIN 26
#define BOARD_EXTRA_GPIO_27_PIN 27
#define BOARD_EXTRA_GPIO_28_PIN 28

#define BOARD_YELLOW_LED_PIN 29