// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------- //
// rmii_refclk //
// ----------- //

#define rmii_refclk_wrap_target 0
#define rmii_refclk_wrap 1
#define rmii_refclk_pio_version 1

static const uint16_t rmii_refclk_program_instructions[] = {
            //     .wrap_target
    0xb842, //  0: nop                    side 1
    0xb042, //  1: nop                    side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program rmii_refclk_program = {
    .instructions = rmii_refclk_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = rmii_refclk_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config rmii_refclk_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + rmii_refclk_wrap_target, offset + rmii_refclk_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

